name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'ğŸš€ New Features'
    label: 'feature'
  - title: 'ğŸ› Bug Fixes'
    label: 'bug'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
